const loader=document.querySelector('.loader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),500));
const reveals=document.querySelectorAll('.reveal');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});reveals.forEach(el=>io.observe(el));
const tower=document.querySelector('.tower');window.addEventListener('scroll',()=>{const y=window.scrollY,r=Math.min(y/window.innerHeight,1);if(tower){tower.style.transform=`rotateY(${-19-r*28}deg) rotateX(${3+r*7}deg) translateY(${r*90}px) scale(${1+r*.08})`;tower.style.filter=`brightness(${1-r*.22})`}});
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav nav');if(menu)menu.addEventListener('click',()=>nav.classList.toggle('open'));
const cards=[...document.querySelectorAll('.property-card')];const search=document.querySelector('#search'),typeFilter=document.querySelector('#typeFilter'),areaFilter=document.querySelector('#areaFilter'),bhkFilter=document.querySelector('#bhkFilter'),priceFilter=document.querySelector('#priceFilter');
function filterProperties(){const q=(search.value||'').toLowerCase();let count=0;cards.forEach(c=>{const okQ=!q||c.dataset.name.toLowerCase().includes(q)||c.dataset.area.toLowerCase().includes(q)||c.dataset.type.toLowerCase().includes(q);const okT=typeFilter.value==='all'||c.dataset.type===typeFilter.value;const okA=areaFilter.value==='all'||c.dataset.area===areaFilter.value;const okB=bhkFilter.value==='all'||c.dataset.bhk===bhkFilter.value;const max=priceFilter.value==='all'?Infinity:Number(priceFilter.value);const okP=Number(c.dataset.price)<=max;const show=okQ&&okT&&okA&&okB&&okP;c.classList.toggle('hidden',!show);if(show)count++});document.querySelector('#resultCount').textContent=`${count} residence${count===1?'':'s'}`}
[search,typeFilter,areaFilter,bhkFilter,priceFilter].forEach(x=>x.addEventListener('input',filterProperties));function resetFilters(){search.value='';typeFilter.value='all';areaFilter.value='all';bhkFilter.value='all';priceFilter.value='all';filterProperties()}function setArea(area){areaFilter.value=area;filterProperties()}
let favorites=new Set;function saveProperty(btn,e){e.stopPropagation();const card=btn.closest('.property-card');const name=card.dataset.name;if(favorites.has(name)){favorites.delete(name);btn.textContent='♡'}else{favorites.add(name);btn.textContent='♥'}document.querySelector('#favCount').textContent=favorites.size}function toggleFavorites(){cards.forEach(c=>c.classList.toggle('hidden',favorites.size>0&&!favorites.has(c.dataset.name)));document.querySelector('#resultCount').textContent=favorites.size?`${favorites.size} saved residence${favorites.size===1?'':'s'}`:`${cards.length} residences`}
function modal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){document.getElementById(id).classList.remove('open');document.body.style.overflow=''}document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))});
function openProperty(title,price,meta,area){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalPrice').textContent=`₹ ${price}`;document.querySelector('#modalMeta').textContent=`${meta} · ${area}`;modal('propertyModal')}
function openVisit(){document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'));modal('visitModal')}
let floor=20;function openProject(){modal('projectModal');renderFloor(floor)}function setFloor(v){floor=Number(v);renderFloor(floor)}function changeFloor(delta){floor=Math.max(1,Math.min(38,floor+delta));document.querySelector('#floorRange').value=floor;renderFloor(floor)}function renderFloor(f){document.querySelector('#floorLabel').textContent=`Floor ${f}`;const building=document.querySelector('#building3d');building.style.transform=`perspective(900px) rotateY(${-25+f*.25}deg) rotateX(${f%2?1:-1}deg)`;const box=document.querySelector('#apartments');box.innerHTML='';for(let i=1;i<=6;i++){const sold=((f+i)%7===0);const el=document.createElement('button');el.className=`apt ${sold?'sold':'available'}`;el.innerHTML=`<strong>A${f}${String(i).padStart(2,'0')}</strong><span>${sold?'SOLD':'AVAILABLE'} · ${i<3?'2':'3'} BHK</span>`;el.onclick=()=>{if(!sold)openProperty(`The Marquis · A${f}${String(i).padStart(2,'0')}`,`${(2.1+i*.23).toFixed(2)} Cr`,`${i<3?'2':'3'} BHK · Floor ${f}`,'Kokapet')};box.appendChild(el)}}
function submitLead(e){e.preventDefault();const d=new FormData(e.target);const subject=encodeURIComponent('Aurelia Estates — Private Consultation');const body=encodeURIComponent(`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nInterest: ${d.get('type')}`);window.location.href=`mailto:hello@aureliaestates.in?subject=${subject}&body=${body}`;return false}
function submitVisit(e){e.preventDefault();const d=new FormData(e.target);const subject=encodeURIComponent('Aurelia Estates — Site Visit Request');const body=encodeURIComponent(`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nProperty: ${d.get('property')}\nPreferred date: ${d.get('date')||'Flexible'}`);window.location.href=`mailto:hello@aureliaestates.in?subject=${subject}&body=${body}`;return false}
