const loader=document.querySelector('.loader');window.addEventListener('load',()=>setTimeout(()=>loader.classList.add('hide'),500));
const reveals=document.querySelectorAll('.reveal');const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});reveals.forEach(el=>io.observe(el));
const tower=document.querySelector('.tower');window.addEventListener('scroll',()=>{const y=window.scrollY,r=Math.min(y/window.innerHeight,1);if(tower){tower.style.transform=`rotateY(${-19-r*28}deg) rotateX(${3+r*7}deg) translateY(${r*90}px) scale(${1+r*.08})`;tower.style.filter=`brightness(${1-r*.22})`}});
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav nav');if(menu)menu.addEventListener('click',()=>nav.classList.toggle('open'));
const cards=[...document.querySelectorAll('.property-card')];const search=document.querySelector('#search'),typeFilter=document.querySelector('#typeFilter'),areaFilter=document.querySelector('#areaFilter'),bhkFilter=document.querySelector('#bhkFilter'),priceFilter=document.querySelector('#priceFilter');
function filterProperties(){const q=(search.value||'').toLowerCase();let count=0;cards.forEach(c=>{const okQ=!q||c.dataset.name.toLowerCase().includes(q)||c.dataset.area.toLowerCase().includes(q)||c.dataset.type.toLowerCase().includes(q);const okT=typeFilter.value==='all'||c.dataset.type===typeFilter.value;const okA=areaFilter.value==='all'||c.dataset.area===areaFilter.value;const okB=bhkFilter.value==='all'||c.dataset.bhk===bhkFilter.value;const max=priceFilter.value==='all'?Infinity:Number(priceFilter.value);const okP=Number(c.dataset.price)<=max;const show=okQ&&okT&&okA&&okB&&okP;c.classList.toggle('hidden',!show);if(show)count++});document.querySelector('#resultCount').textContent=`${count} residence${count===1?'':'s'}`}
[search,typeFilter,areaFilter,bhkFilter,priceFilter].forEach(x=>x.addEventListener('input',filterProperties));function resetFilters(){search.value='';typeFilter.value='all';areaFilter.value='all';bhkFilter.value='all';priceFilter.value='all';filterProperties()}function setArea(area){areaFilter.value=area;filterProperties()}
let favorites=new Set;function saveProperty(btn,e){e.stopPropagation();const card=btn.closest('.property-card');const name=card.dataset.name;if(favorites.has(name)){favorites.delete(name);btn.textContent='♡'}else{favorites.add(name);btn.textContent='♥'}document.querySelector('#favCount').textContent=favorites.size}function toggleFavorites(){cards.forEach(c=>c.classList.toggle('hidden',favorites.size>0&&!favorites.has(c.dataset.name)));document.querySelector('#resultCount').textContent=favorites.size?`${favorites.size} saved residence${favorites.size===1?'':'s'}`:`${cards.length} residences`}
function modal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){document.getElementById(id).classList.remove('open');document.body.style.overflow=''}document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))});
function openProperty(title,price,meta,area){document.querySelector('#modalTitle').textContent=title;document.querySelector('#modalPrice').textContent=`₹ ${price}`;document.querySelector('#modalMeta').textContent=`${meta} · ${area}`;modal('propertyModal')}
function openVisit(){document.querySelectorAll('.modal.open').forEach(m=>m.classList.remove('open'));modal('visitModal')}
let floor=20;function openProject(){modal('projectModal');renderFloor(floor)}function setFloor(v){floor=Number(v);renderFloor(floor)}function changeFloor(delta){floor=Math.max(1,Math.min(38,floor+delta));document.querySelector('#floorRange').value=floor;renderFloor(floor)}function renderFloor(f){document.querySelector('#floorLabel').textContent=`Floor ${f}`;const building=document.querySelector('#building3d');building.style.transform=`perspective(900px) rotateY(${-25+f*.25}deg) rotateX(${f%2?1:-1}deg)`;const box=document.querySelector('#apartments');box.innerHTML='';for(let i=1;i<=6;i++){const sold=((f+i)%7===0);const el=document.createElement('button');el.className=`apt ${sold?'sold':'available'}`;el.innerHTML=`<strong>A${f}${String(i).padStart(2,'0')}</strong><span>${sold?'SOLD':'AVAILABLE'} · ${i<3?'2':'3'} BHK</span>`;el.onclick=()=>{if(!sold)openProperty(`The Marquis · A${f}${String(i).padStart(2,'0')}`,`${(2.1+i*.23).toFixed(2)} Cr`,`${i<3?'2':'3'} BHK · Floor ${f}`,'Kokapet')};box.appendChild(el)}}
function submitLead(e){e.preventDefault();const d=new FormData(e.target);const subject=encodeURIComponent('Aurelia Estates — Private Consultation');const body=encodeURIComponent(`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nInterest: ${d.get('type')}`);window.location.href=`mailto:hello@aureliaestates.in?subject=${subject}&body=${body}`;return false}
function submitVisit(e){e.preventDefault();const d=new FormData(e.target);const subject=encodeURIComponent('Aurelia Estates — Site Visit Request');const body=encodeURIComponent(`Name: ${d.get('name')}\nPhone: ${d.get('phone')}\nProperty: ${d.get('property')}\nPreferred date: ${d.get('date')||'Flexible'}`);window.location.href=`mailto:hello@aureliaestates.in?subject=${subject}&body=${body}`;return false}

/* PREMIUM 3D EXPERIENCE */
(()=>{
 const style=document.createElement('style');style.textContent=`
 .property-grid{perspective:1800px}
 .property-card{transform-style:preserve-3d;will-change:transform;position:relative;transition:transform .16s ease,filter .35s ease}
 .property-card:hover{z-index:5;filter:drop-shadow(0 30px 45px rgba(0,0,0,.18))}
 .property-image{transform-style:preserve-3d;will-change:transform;box-shadow:0 22px 55px rgba(0,0,0,.16)}
 .property-image:before{content:'';position:absolute;inset:-30%;z-index:3;pointer-events:none;background:linear-gradient(110deg,transparent 38%,rgba(255,255,255,.28) 49%,transparent 60%);transform:translateX(-80%) rotate(8deg);transition:transform .9s cubic-bezier(.2,.7,.2,1)}
 .property-card:hover .property-image:before{transform:translateX(80%) rotate(8deg)}
 .property-image:after{transition:opacity .5s ease}.property-card:hover .property-image:after{opacity:.72}
 .tower,.project-building{transform-style:preserve-3d;backface-visibility:hidden}
 .tower:after,.project-building:after{content:'';position:absolute;inset:0;pointer-events:none;background:linear-gradient(110deg,transparent 30%,rgba(255,255,255,.18) 47%,transparent 60%);transform:translateX(-120%);animation:premiumGlassSweep 7s ease-in-out infinite}
 .project-building{animation:premiumBuildingFloat 6s ease-in-out infinite}
 .project-orb{animation:premiumOrb 5s ease-in-out infinite}
 .project-ring{animation:premiumRing 4s ease-in-out infinite}
 .hero .stars{animation:premiumStars 20s linear infinite}
 .hero-copy,.hero-side,.hero-bottom{transform-style:preserve-3d}
 @keyframes premiumGlassSweep{0%,30%{transform:translateX(-120%)}65%,100%{transform:translateX(120%)}}
 @keyframes premiumBuildingFloat{0%,100%{transform:perspective(900px) rotateY(-17deg) translate3d(0,0,0)}50%{transform:perspective(900px) rotateY(-12deg) translate3d(0,-16px,18px)}}
 @keyframes premiumOrb{50%{transform:translate3d(18px,-20px,0) scale(1.08)}}
 @keyframes premiumRing{50%{transform:rotate(-12deg) scale(1.05);opacity:.7}}
 @keyframes premiumStars{to{background-position:110px 220px}}
 @media(prefers-reduced-motion:reduce){.property-card{transform:none!important}.property-image:before,.tower:after,.project-building:after{animation:none!important}}
 `;document.head.appendChild(style);
 const tiltCards=()=>document.querySelectorAll('.property-card').forEach(card=>{
   if(card.dataset.tiltBound)return;card.dataset.tiltBound='1';
   const image=card.querySelector('.property-image');
   card.addEventListener('pointermove',e=>{if(window.matchMedia('(max-width:900px)').matches)return;const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`rotateX(${(-y*7).toFixed(2)}deg) rotateY(${(x*9).toFixed(2)}deg) translateZ(8px)`;if(image)image.style.transform=`translateZ(22px) scale(1.025) rotateX(${(-y*2).toFixed(2)}deg) rotateY(${(x*3).toFixed(2)}deg)`});
   card.addEventListener('pointerleave',()=>{card.style.transform='';if(image)image.style.transform=''})
 });
 tiltCards();
 const grid=document.querySelector('.property-grid');if(grid)new MutationObserver(tiltCards).observe(grid,{childList:true,subtree:true});
 const project=document.querySelector('.project-visual');
 if(project&&!window.matchMedia('(max-width:900px)').matches){project.addEventListener('pointermove',e=>{const r=project.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;const b=document.querySelector('.project-building');if(b)b.style.marginLeft=`${x*28}px`;const orb=document.querySelector('.project-orb');if(orb)orb.style.marginLeft=`${x*35}px`;project.style.backgroundPosition=`${50+x*5}% ${45+y*5}%`});project.addEventListener('pointerleave',()=>{const b=document.querySelector('.project-building');if(b)b.style.marginLeft='';project.style.backgroundPosition=''})}
 const hero=document.querySelector('.hero');
 if(hero&&!window.matchMedia('(max-width:900px)').matches){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;const copy=document.querySelector('.hero-copy');const wrap=document.querySelector('.tower-wrap');if(copy)copy.style.transform=`translate3d(${x*-10}px,${y*-7}px,0)`;if(wrap)wrap.style.transform=`translate3d(${x*18}px,${y*12}px,0)`});hero.addEventListener('pointerleave',()=>{const copy=document.querySelector('.hero-copy'),wrap=document.querySelector('.tower-wrap');if(copy)copy.style.transform='';if(wrap)wrap.style.transform=''})}
})();

/* CLAYMORPHIC 3D REAL-ESTATE MODE */
(()=>{
 const s=document.createElement('style');s.textContent=`
 :root{--clay:#e8dfd2;--clay2:#f6f0e8;--clay3:#d1c5b6;--ink:#30302e;--clay-shadow:rgba(72,61,48,.22)}
 body{background:var(--clay2);color:var(--ink)}
 .nav{background:rgba(238,232,223,.76);border-bottom:1px solid rgba(74,62,49,.1);box-shadow:0 10px 35px rgba(75,62,46,.08)}
 .nav nav{color:#5c574f}.nav nav a:hover{color:#8b6d49}.nav-cta{color:#3d3934;border-color:#b9ac9d;background:#eee6dc;box-shadow:inset 2px 2px 5px #fff8,inset -3px -3px 7px #b9ac9d55,5px 8px 18px #8b796522}
 .hero{background:radial-gradient(circle at 72% 42%,#f4eee5 0,#ddd2c4 32%,#bfb0a0 68%,#9f8f7d 100%);color:#302d29}
 .hero-bg{background:linear-gradient(115deg,#f2ebe1cc 8%,transparent 65%),linear-gradient(0deg,#b9aa99aa,transparent 42%)}
 .stars{opacity:.18;background-image:radial-gradient(#5c5145 1.2px,transparent 1.2px)}
 .hero h1{color:#332f2a;text-shadow:2px 3px 0 #fff7,8px 12px 22px #6b594533}.hero h1 em{color:#8b6b45}.hero-text{color:#5e564d}.hero-side{color:#5c554d}.scroll-line{background:linear-gradient(#806343,transparent)}
 .hero-bottom{color:#645b50}.button.primary{background:#e9ded0;color:#352f29;box-shadow:inset 2px 2px 5px #fff9,inset -5px -5px 10px #aa978455,7px 12px 22px #66554225}.button.primary:hover{transform:translateY(-4px) scale(1.02);box-shadow:inset 2px 2px 5px #fff9,inset -5px -5px 10px #aa978455,10px 18px 30px #66554235}
 .tower-wrap{filter:drop-shadow(35px 45px 35px rgba(67,52,37,.25))}.tower{background:linear-gradient(90deg,#b8aa9b,#eee5d9 42%,#a89a8b 72%,#857769);box-shadow:inset 12px 0 25px #fff5,inset -18px -5px 35px #65554455,35px 40px 70px #5a493533;clip-path:polygon(18% 0,82% 0,100% 100%,0 100%)}.tower:before{background:repeating-linear-gradient(to right,transparent 0 18px,#fff4 19px 20px),repeating-linear-gradient(to bottom,transparent 0 30px,#7b6b5b25 31px 32px)}.tower-core{background:#fff3}.floor{background:#6f5e4c38}.tower-base{background:linear-gradient(90deg,#8f7d6a,#ded2c4,#806e5c);box-shadow:inset 4px 4px 8px #fff5,inset -6px -6px 12px #65513f44}
 .intro{background:#f4eee6;color:#35312d}.intro-copy{color:#6a6259}.section-number{color:#887c6f}.intro h2,.section-head h2,.contact h2{color:#39342f}
 .properties{background:#e7dfd4;color:#35312d}.properties .eyebrow,.locations .eyebrow{color:#827467}.filters input,.filters select{background:#eee7de;border:0;box-shadow:inset 3px 3px 8px #b7a99955,inset -3px -3px 8px #fff8,0 8px 20px #77645012}.result-bar{border-color:#c8bdb0;color:#7b7065}
 .property-grid{perspective:1800px}.property-card{background:#e9e1d6;border-radius:28px;padding:10px;box-shadow:10px 15px 30px #78675320,inset 2px 2px 5px #fff8,inset -3px -3px 7px #aa9a8a55;overflow:hidden}.property-card:hover{filter:drop-shadow(0 28px 35px #66554235)}
 .property-image{height:500px;border-radius:21px;background-color:#cfc2b2;box-shadow:inset 4px 5px 12px #fff6,inset -8px -8px 18px #6c594733,0 12px 22px #5b4b3c1c}.property-image:after{background:linear-gradient(0deg,#4c3b2d55,transparent 48%)}.tag{background:#f1e9dfdd;color:#51463b;border-radius:999px;box-shadow:inset 1px 1px 3px #fff,inset -2px -2px 4px #9d8c7b55}.heart{background:#eee4d8dd;color:#675644;border:0;box-shadow:inset 2px 2px 5px #fff9,inset -3px -3px 6px #a5928055,3px 5px 12px #6c594433}.property-info{padding:20px 8px 14px}.property-info p,.property-meta{color:#827568}.property-meta{border-color:#c9bdb0}.property-meta button{color:#51473e}
 .projects{background:#c9bbab}.project-visual{background:radial-gradient(circle at 50% 40%,#eee5d9 0,#c8b8a7 38%,#8d7a68 100%)}.project-building{background:linear-gradient(90deg,#a79583,#f0e8de 45%,#8e7c69);box-shadow:inset 12px 0 24px #fff6,inset -20px -5px 35px #5f4b3c55,35px 35px 70px #57463544}.project-building:before{background:repeating-linear-gradient(to bottom,transparent 0 37px,#fff5 38px 40px),repeating-linear-gradient(to right,transparent 0 24px,#6b59482a 25px 26px)}.project-orb{background:#fff5;filter:blur(30px)}.project-ring{border-color:#fff8}.viewer-trigger{border:0;background:#e9dfd3;color:#493d32;box-shadow:inset 2px 2px 5px #fff9,inset -4px -4px 8px #9f8d7b55,7px 10px 22px #55443333}
 .project-copy{color:#38322d}.project-copy>p:not(.eyebrow){color:#655b51}.project-stats{border-color:#ffffff55}.project-stats span{color:#76695d}
 .locations{background:#e5ddd2;color:#38322d}.location-list,.location{border-color:#c7baac}.location p{color:#7a6d61}.location b{color:#78604a}
 .statement{background:linear-gradient(135deg,#e6ddd2,#bcae9f);color:#39332e}.statement em{color:#806242}.round-arrow{color:#4d4136;border-color:#806f5d66;background:#e7ddd1;box-shadow:inset 2px 2px 5px #fff9,inset -4px -4px 8px #98857555,7px 12px 22px #57453433}
 .contact{background:#cbbba8;color:#3a332c}.contact-copy{color:#5f5449}.contact label{color:#67594c}.contact input,.contact select{border-color:#806f5e55}.contact input::placeholder{color:#7a6d60}
 footer{background:#8e7c6a;color:#e8dfd4;border-color:#ffffff18}
 .modal{background:#5a4b3dcc}.modal-card{background:#e7ded2;color:#38322d;border:0;border-radius:32px;box-shadow:25px 35px 80px #241b1433,inset 2px 2px 8px #fff8,inset -5px -5px 12px #806c5b55}.close{background:#e5dacf;color:#55483d;border:0;box-shadow:inset 2px 2px 4px #fff,inset -3px -3px 6px #8d7b6a55}.modal-body>p:not(.eyebrow){color:#6b6056}.amenities{border-color:#c7baac;color:#70645a}.floor-viewer{background:radial-gradient(circle at 35% 45%,#eadfd3,#b5a493 65%,#8b7764);border-radius:22px}.building-3d{background:repeating-linear-gradient(to bottom,#b8a795 0 10px,#8d7a68 11px 22px),linear-gradient(90deg,#776453,#e9dfd4,#887564);box-shadow:inset 10px 0 20px #fff5,inset -12px -8px 25px #604b3b55,30px 30px 55px #4d3b2c44}.floor-controls{background:#e7ddd1dd;border:0;box-shadow:inset 2px 2px 5px #fff,inset -4px -4px 8px #8d796655,0 12px 25px #4f3d2d33}.floor-controls button{background:#b49779;color:#fff;box-shadow:inset 2px 2px 4px #fff6,inset -3px -3px 5px #725a44}.floor-controls input{accent-color:#8c6d4d}.apartment-panel{background:#dfd4c7dd;border:0;border-radius:22px;box-shadow:inset 2px 2px 7px #fff8,inset -4px -4px 10px #88746455}.apt{border:0;border-radius:14px;background:#e8dfd4;color:#4a4037;box-shadow:inset 2px 2px 4px #fff,inset -3px -3px 6px #9b887655,4px 6px 12px #5e4b3b22}.apt.available{border:0}.apt.sold{opacity:.45}.visit-modal input,.visit-modal select{color:#443a31;border-color:#a08f7f66}
 .clay-orb{position:absolute;border-radius:50%;pointer-events:none;background:radial-gradient(circle at 32% 28%,#fff9,#d8c7b5 42%,#a28d78 100%);box-shadow:inset 14px 14px 25px #fff7,inset -20px -25px 35px #6b554444,20px 30px 45px #5d4b3a33;filter:saturate(.7)}
 .hero:after{content:'';position:absolute;width:210px;height:210px;border-radius:50%;right:38%;top:13%;background:radial-gradient(circle at 30% 25%,#fff9,#d9c8b6 45%,#9b856f);box-shadow:inset 15px 15px 28px #fff8,inset -22px -25px 38px #634d3a44,18px 25px 45px #5a483733;opacity:.75;animation:clayFloat 7s ease-in-out infinite;pointer-events:none}
 .hero .tower-wrap{z-index:2}.hero-copy{z-index:4}
 @keyframes clayFloat{0%,100%{transform:translate3d(0,0,0) rotate(0)}50%{transform:translate3d(-20px,18px,0) rotate(8deg)}}
 @media(max-width:900px){.hero:after{width:130px;height:130px;right:8%;top:12%}.property-card{border-radius:24px}.property-image{border-radius:18px}}
 @media(prefers-reduced-motion:reduce){.hero:after{animation:none}}
 `;document.head.appendChild(s);
 document.querySelectorAll('.property-card').forEach(c=>{c.addEventListener('mouseenter',()=>c.style.setProperty('--clay-lift','1'));c.addEventListener('mouseleave',()=>c.style.setProperty('--clay-lift','0'))});
})();
